### ISSUE TITLE
sliMpd php erors

### ISSUE THREAD

**Issue by killhellokitty** [othmar52/slimpd#5]
I made the additions/changes per your new instruction set and am still stuck at the same place with sliMpd unfortunately.  I get this error in the 'lighttpd' logs:

`<2016-07-15 12:06:29: (mod_fastcgi.c.2520) FastCGI-stderr: Stack trace:
2016-07-15 12:06:29: (mod_fastcgi.c.2520) FastCGI-stderr: #0 /srv/http/slimpd/php/libs/twig/SlimpdTwigExtension.php(27): Slimpd\AbstractModel::getRandomInstance()
2016-07-15 12:06:29: (mod_fastcgi.c.2520) FastCGI-stderr: #1 /srv/http/slimpd/vendor-dist/twig/twig/lib/Twig/Environment.php(403) : eval()'d code(19): Slimpd_Twig_Extension->getRandomInstance('Track')
2016-07-15 12:06:29: (mod_fastcgi.c.2520) FastCGI-stderr: #2 /srv/http/slimpd/vendor-dist/twig/twig/lib/Twig/Template.php(381): __TwigTemplate_badbcc4ac5692dcc69466027198c817974b547369180bfb5b35f0cfdbf8eae0b->doDisplay(Array, Array)
2016-07-15 12:06:29: (mod_fastcgi.c.2520) FastCGI-stderr: #3 /srv/http/slimpd/vendor-dist/twig/twig/lib/Twig/Template.php(355): Twig_Template->displayWithErrorHandling(Array, Array)
2016-07-15 12:06:29: (mod_fastcgi.c.2520) FastCGI-stderr: #4 /srv/http/slimpd/vendor-dist/twig/twig/lib/Twig/Environment.php(403) : eval()'d code(23): Twig_Template->display(Array)
2016-07-15 12:06:29: (mod_fastcgi.c.2520) FastCGI-stderr: #5 /srv/http/slimpd/vendor-dist/twig/twig/lib/Twig/Template.php(381): __TwigTemplate_2f62b3d91966f2195c056c5b0674d2ebf3fd789c09a5195ee3e50e9864e1a6dd->doDisplay(Array, Array)
2016-07-15 12:06:29: (mod_fastcgi.c.2520) FastCGI-stderr: #6 /srv/http/slimpd/vendor-dist/twig/twig/lib/ in /srv/http/slimpd/php/models/AbstractModel.php on line 487>`

It just repeats this error message over and over in the log.   Other than that, I am still not sure what to do to get sliMpd to work.  I am persistant.
Thanks,
Josh

**Comment by othmar52** [comment]
please make sure you have enabled mod_rewrite in `/etc/lighttpd/lighttpd.conf` by replacing the line
```
server.modules = (
#    "mod_rewrite",
```
with
```
server.modules = (
    "mod_rewrite",
```

and you have to add this line anywhere in `/etc/lighttpd/lighttpd.conf`
```
url.rewrite-if-not-file = ("(.*)" => "/index.php/$0")
```

Further i found some invalid variable-names in `config/config_local.sample.ini`. Please pull the the latest commit in masterbranch and try to figure it out yourself! You should get redirected to the new route `/systemcheck` where you find a hint how to fix this specific configuration-error (which should never appear again).

In case you really can't find the problem look at the latest changes in [`config/config_local.sample.ini`](https://github.com/othmar52/slimpd/commit/c95b722f7dc07ad415e4c470b891cf60db04ab40) and update those variable-names in your git-ignored `config/config_local.ini` accordingly.

**Comment by killhellokitty** [comment]
I have done as instructed.  I found that I had not properly created the mysql database, that is now fixed.  At the same time the _/systemcheck_; I have been unable to get it to work.  Clicking on any item; such as 'Library' gives a 404 error. And the html for the page isn't loading properly.  The previous error I had posted appears to have been corrected.  I am however still stuck in limbo with the app.  here is a link to what it looks like now:  [(http://s725.photobucket.com/user/killhellokitty1/media/sliMpd_zps1kxzpswr.png.html)]

**Comment by othmar52** [comment]
obviously mod_rewrite still does not work. did you restart lighthttp after activating mod_rewrite?

**Comment by killhellokitty** [comment]
yes I did restart lighttpd after updating the mod_rewrite. 'sytemctl
restart lighttpd.service'.

**Comment by othmar52** [comment]
Does your documentroot exactly point to the directory of index.php in your lighttpd configuration?
or do you have to add a subdirectory in the url?

Do you see an image when accessing an url like this?
[http://_your-slimpd-hostname_/skin/default/img/playing.gif](http://your-slimpd-hostname/skin/default/img/playing.gif)

or do you need to add another directory until you see the image
[http://_your-slimpd-hostname_/**another-directory**/skin/default/img/playing.gif](http://your-slimpd-hostname/another-directory/skin/default/img/playing.gif)

Of course you have to replace _your-slimpd-hostname_ with localhost, ip or whatever you have configured in your webserver-configuration in this url.

**Comment by killhellokitty** [comment]
Yes I can see the image.  I access it like this:
*http://**127.0.0.1/slimpd/skin/default/img/playing.gif
<http://127.0.0.1/slimpd/skin/default/img/playing.gif>*

To get to the page I had sent the last image of, I have to go to:
*http://127.0.0.1/slimpd/index.php <http://127.0.0.1/slimpd/index.php>*

**Comment by killhellokitty** [comment]
I made the change to lighttpd.conf to say:
server.document-root = "/srv/http/slimpd"

That seems to have fixed it.  I can move about the app now and see the
music collection.  However I can not play any music.  It says its playing
and just stays at 0:00.
Also about half of the language is German, my German isn't that good; not
anymore at least, maybe when I was there.  I loved Germany!  I had a great
time.  Thank you again with helping me to get sliMpd to work.  Now I need
to figure out what is wrong with its ability to play and see if its
possible to replace all the German with English.

**Comment by killhellokitty** [comment]
My bad, all I had to do was change 'local' to 'mpd' now it plays.

It doesn't generate a waveform and it isn't loading any album images.  Plus
the German language thing.

**Comment by killhellokitty** [comment]
Under Artist Genere etc I can't select anything it gives an oops! error.
/artist/16/tracks/page/1/sort/added/desc?null
<http://127.0.0.1/artist/16/tracks/page/1/sort/added/desc?null>

**Comment by othmar52** [comment]
Did you setup your sphinx-index as statet in the [more requirements](https://github.com/othmar52/slimpd/wiki/Installation#more-requirements-will-be-optional-in-future)?

i improved the systemchecks. please pull the latest commits and navigate to [http://127.0.0.1./systemcheck](http://127.0.0.1./systemcheck). it is not finished yet but maybe it will give you some hints how to make your installation working.

there are a few hardcoded german terms left but most of the stuff should be in english. just to make sure - your `config/config_local.ini` does not contain `langkey = de`,right?
```
[config]
langkey = de
```

it would be very helpful if you open another issue with missing translations.
thank you

**Comment by killhellokitty** [comment]
I have run the shpinx-index and the first one runs without problem.  The
second, script however gives this error:
WARNING: failed to scanf pid from pid_file '/var/lib/log/searchd.pid'.
WARNING: indices NOT rotated.

I fixed all the issues listed by systemcheck, except I have this continued
problem:
READ-PERMISSION TO ACCESS MPD'S MUSIC-DIRECTORYERROR: Make sure directory
exists and has read-permissions for the webserver-user
check your configuration config/config_local.ini in section

[mpd]
musicdir = /home/jo-shva/Music/

READACCESS TO DATABASEFILEERROR: MPD's databasefile
/home/jo-shva/.config/mpd/database is not readable. Make sure the file
exists and your webserver-user has read-permissions
check your configuration config/config_local.ini in section

[mpd]
dbfile = /home/jo-shva/.config/mpd/database

Here are the permissions for both folders and their contents:

getfacl /home/jo-shva/.config/mpd/database
getfacl: Removing leading '/' from absolute path names
# file: home/jo-shva/.config/mpd/database
# owner: jo-shva
# group: users
user::rw-
user:root:r-x
user:http:r-x
group::r--
mask::r-x
other::r--

And for the Music folder and contents:

# file: home/jo-shva/Music/Royksopp # owner: jo-shva # group: users
user::rwx user:root:r-x user:http:r-x group::r-x mask::r-x other::r-x #
file: home/jo-shva/Music/Siouxsie and The Banshees - Discography # owner:
jo-shva # group: users user::rwx user:root:r-x user:http:r-x group::r-x
mask::r-x other::r-x # file: home/jo-shva/Music/The Killers # owner:
jo-shva # group: users user::rwx user:root:r-x user:http:r-x group::r-x
mask::r-x other::r-x

etc...

I cant figure this one out. Acl should give 'http' and 'root' permission to
these files. These files are also listed in the php.ini under
'open_basedir'. If you have any ideas I sure would appreciate it.

**Comment by othmar52** [comment]
i have created separate issues for the remaining errors
[rotating sphinx index does not work](https://github.com/othmar52/slimpd/issues/7)
[permissions to access musicfiles](https://github.com/othmar52/slimpd/issues/8)

**Comment by othmar52** [comment]
> **Option 2:** change your `config/config_local.conf` to access sliMpd via [http://localhost/slimpd](http://localhost/slimpd)
> 
> ```
> [config]
> absRefPrefix = /slimpd/
> ```
> 
> I recommend **Option 1** because option 2 is not tested at all (but should work theoretically)

In the meantime i  have have [fixed](https://github.com/othmar52/slimpd/commit/85f580ccf3aafcdba43ea42f51a725b755866b6c) this. Feel free to try **Option 2**

**Comment by othmar52** [comment]
now `mod_rewrite` is not required anymore
the default configuration runs without mod_rewrite

```
[config]
; default setup without mod_rewrite
absRefPrefix = /index.php/
absFilePrefix = /

; example setup with activated mod_rewrite
;absRefPrefix = /
;absFilePrefix = /

; example setup without mod_rewrite running slimpd in a subdirectory like http://localhost/slimpd
;absRefPrefix = /slimpd/index.php/
;absFilePrefix = /slimpd/
```

**Comment by killhellokitty** [comment]
This is the setup I went with:

; example setup without mod_rewrite running slimpd in a subdirectory
like http://localhost/slimpd
absRefPrefix = /slimpd/index.php/
absFilePrefix = /slimpd/

This way is more to my liking.  I can still have other folders, etc.
listed under localhost this way.

The default setup that you listed, I did try first, but It would not
work properly for some reason.  So I went with my preferred way.  It
worked doing it this way.  I can't say why.

And, yes, I did remove: server.modules += ("mod_rewrite")

url.rewrite-if-not-file = ("(.*)" => "/index.php/$0")

and changed  server.document-root = "/srv/http/slimpd" To
server.document-root	= "/srv/http/"
